runtime: python39
entrypoint: gunicorn -b :$PORT main:app

instance_class: F4_1G  # 1GB RAM instance for TensorFlow

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: auto

env_variables:
  GCLOUD_STORAGE_BUCKET: "landcover-prediction-bucket"  # Replace with your actual bucket name
